// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 155 start
    // url: process.env["DATABASE_URL"],
    url: process.env["DATABASE_URL_UNPOOLED"],
    // 155 end
  },
});
